### ISSUE TITLE
G14 Object Destroyed After Hibernate/Sleep

### ISSUE THREAD

**Issue by Spazzinq** [aredden/electron-G14Control#15]
![image](https://user-images.githubusercontent.com/26337405/102831222-39a41f00-43b9-11eb-80de-b844a79acaab.png)

**Comment by aredden** [comment]
What version are you using? Also, can you give me some details about what happened before this error occured?

**Comment by Spazzinq** [comment]
0.1.31 (and previous versions but probably with different line #s)

I put my laptop into hibernation mode (I set my lid closing to hibernate it), and upon waking the UI doesn't appear, instead displaying this error.

**Comment by aredden** [comment]
I tested this issue and it didn't happen for me. Does it still happen? Or is it an issue that is still occurring.

**Comment by Spazzinq** [comment]
Looks like it doesn't for me anymore. Thanks for the fix!
