### ISSUE TITLE
Fan Curve Editor allows to create more than 1 plan with the same name

### ISSUE THREAD

**Issue by IGonza** [aredden/electron-G14Control#18]
As mentioned in the title, I can create multiple plans with the same name. This causes several issues:
1. it's not possible to delete 1 of them, only all or nothing.
2. If 1 is assigned to G14Control Plans, there is no way to delete others with the same name

I would check the name for uniqueness when Save Configuration clicked.

**Comment by aredden** [comment]
I knew about this issue, but sort of ignored it back when I built the feature because I had other stuff to focus on. I will get that sorted at some point.

**Comment by aredden** [comment]
I think this issue is resolved in the most recent update.
