### ISSUE TITLE
dev setup questions

### ISSUE THREAD

**Issue by IGonza** [aredden/electron-G14Control#20]
Getting some warnings from npm during npm install. I'm not familiar with node.js , so not sure if this is some critical issue and what I should do about it:

`D:\Projects\G14Control\electron-G14Control>npm audit

                       === npm audit security report ===

# Run  npm install --save-dev react-scripts@4.0.1  to resolve 1 vulnerability
SEMVER WARNING: Recommended action is a potentially breaking change

  High            Prototype Pollution

  Package         object-path

  Dependency of   react-scripts [dev]

  Path            react-scripts > resolve-url-loader > adjust-sourcemap-loader
                  > object-path

  More info       https://npmjs.com/advisories/1573

                                 Manual Review
             Some vulnerabilities require your attention to resolve

          Visit https://go.npm.me/audit-guide for additional guidance

  Low             Regular Expression Denial of Service

  Package         braces

  Patched in      >=2.3.1

  Dependency of   babel-cli [dev]

  Path            babel-cli > chokidar > anymatch > micromatch > braces

  More info       https://npmjs.com/advisories/786

found 2 vulnerabilities (1 low, 1 high) in 2857 scanned packages
  1 vulnerability requires semver-major dependency updates.
  1 vulnerability requires manual review. See the full report for details.`

**Comment by aredden** [comment]
The major vulnerability is from babel, which doesn't actually stay a part of the app after compilation, so it's fine. It's just a part of react-scripts. I get those errors as well.
