### ISSUE TITLE
Add custom CPU Tuning presets

### ISSUE THREAD

**Issue by jQubz** [aredden/electron-G14Control#23]
I would love to see a possibility of making my own custom presets in CPU Tuning. Adding them to a plan would also be very nice.

**Comment by aredden** [comment]
That would be cool, and I do want to do that personally, I'm just afraid that people will make custom plans that are dangerous. For example, before I had the minimum/maximum values set, my friend set his tdp to 1 watt and got a bsod lol.

**Comment by jQubz** [comment]
Haha, that's good :D Well, you already allow users to change and apply not sane values tbh, but I totally get your point. Personally I would like to go even lower on power consumption to like 15W TDP (so basically 4800U instead of HS in my case). How about something like an advanced switch then? Or even better just hard block to some sane values like STAPM lower than 5W or more than 50W is probably not good and can be blocked (we would need to find info on these values for other parameters though)

**Comment by smefa** [comment]
+1

**Comment by aredden** [comment]
This update gives cpu tuning presets :)
