### ISSUE TITLE
When applying a plan, the cpu preset doesnt get applied correctly

### ISSUE THREAD

**Issue by Filechaser** [aredden/electron-G14Control#30]
![image](https://user-images.githubusercontent.com/13608679/103664557-b4049f80-4f72-11eb-81df-160683ab493e.png)
It stayed the same when using the button "apply this plan" It should have used the Cpu plan "performance" and therefore a higher tdp

![image](https://user-images.githubusercontent.com/13608679/103664742-e1e9e400-4f72-11eb-84c9-34af5a7b1015.png)

**Comment by Filechaser** [comment]
ok thanks for adding custom cpu tuning profiles.
Yes even on the newest version, the tdp gets reset after boot from standby or hibernation and the plan doesn't get applied correctly

**Comment by aredden** [comment]
Oh yeah, that would happen. When booting everything goes to the windows defaults. I havn't added plan application when you start the program, so that behavior would be expected. I'm more worried about plans not being correctly applied when you unplug / plug-in the laptop.

**Comment by aredden** [comment]
Also, the UI is build with typescript, but using reactjs as a front end framework, redux for front end data storage, and it's built on top of electron-- which basically takes a website running on a single chrome tab and turns it into an app. @Filechaser
