### ISSUE TITLE
Unique G14Control plan name error after deleting plan

### ISSUE THREAD

**Issue by Alan-Cha** [aredden/electron-G14Control#32]
After deleting a G14Control plan, when I try to create a new plan with the same name, I get a "Plan names must be unique" error, even though the plan is deleted.

This issue could be related to #31.

My workaround is similar to what I mentioned in #31. I click on a different tab and go back to the Plans tab.

I am currently running version 0.1.37.

**Comment by aredden** [comment]
I have just fixed this issue. I was able to recreate it and debug and now it should work :)
