### ISSUE TITLE
Fans Constantly ramping up and down, regardless of fan curve

### ISSUE THREAD

**Issue by MdotAmaan** [aredden/electron-G14Control#33]
This was an issue i didn't have on G14control-r2, but when both cpu and gpu are at around 70C, the fans constantly ramp up and down, even if i set the fan curve to be completely flat.

**Comment by aredden** [comment]
That is actually an issue with the laptop itself. It will happen in armoury crate (app) as well when you manually set a fan curve, as well as when you use atrofac. I generally only use custom fans when I know I'm going to be outputting a lot of heat. Also some curves cause oscillation more than others.

**Comment by kaizenblumenblupper** [comment]
So there's no way to tame this and make laptop quieter?

**Comment by MdotAmaan** [comment]
You could set the fans to turn off completely and then ramp up aggressivly under a heavy load. Thats how I've gotten around it, atleast for lighter use
