### ISSUE TITLE
Screen Refresh Rate: Adding it to Power Plans Control

### ISSUE THREAD

**Issue by CleanHit** [aredden/electron-G14Control#53]
Is it possible to add a screen refresh rate change between 60 Hz and 120 Hz to power plans settings? If I understood it correctly then lower screen refresh rates result in less power drain, which can be beneficial e.g. to (custom) power plans that don't involve playing games e.g coding and etc..

**Comment by HemangKumawat** [comment]
From what I know of from people's experiences on reddit. It results in no to negligible change in power draw
